<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Hello</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Include="charcoal.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Charcoal/Charcoal.csproj" />
  </ItemGroup>

</Project>
